// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJAcsAH7ERMcw0tSuyKkZTdWiV-1rkII',
    appId: '1:844890923161:web:248ae7714bc70fd1115808',
    messagingSenderId: '844890923161',
    projectId: 'notif-16e7a',
    authDomain: 'notif-16e7a.firebaseapp.com',
    storageBucket: 'notif-16e7a.appspot.com',
    measurementId: 'G-Q1R9LVKD5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzKi2htcSGhsMu9bxz2k0qjRU-dPFEGsI',
    appId: '1:844890923161:android:f141958c2d034321115808',
    messagingSenderId: '844890923161',
    projectId: 'notif-16e7a',
    storageBucket: 'notif-16e7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwbUmZ3Q1i0uQkS3MzKl6kJEUMRQ1WQ8',
    appId: '1:844890923161:ios:a8600ce1e381da9c115808',
    messagingSenderId: '844890923161',
    projectId: 'notif-16e7a',
    storageBucket: 'notif-16e7a.appspot.com',
    androidClientId: '844890923161-q4l80lsqupj88f175ia75gkeadnutjab.apps.googleusercontent.com',
    iosClientId: '844890923161-bk0u8ppsssus3mgpp1e4c26o8afg5jpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.notif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArwbUmZ3Q1i0uQkS3MzKl6kJEUMRQ1WQ8',
    appId: '1:844890923161:ios:a8600ce1e381da9c115808',
    messagingSenderId: '844890923161',
    projectId: 'notif-16e7a',
    storageBucket: 'notif-16e7a.appspot.com',
    androidClientId: '844890923161-q4l80lsqupj88f175ia75gkeadnutjab.apps.googleusercontent.com',
    iosClientId: '844890923161-bk0u8ppsssus3mgpp1e4c26o8afg5jpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.notif',
  );
}
